name: ${project.name}
version: ${project.version}
main: ${project.group}.${project.name.toLowerCase()}.${project.name}
api-version: 1.18
author: Blugon

permissions:
  moreworld.command:
    description: Visible command
  moreworld.create:
    description: Create new world
  moreworld.remove:
    description: Remove world
  moreworld.teleport:
    description: Teleport world
  moreworld.load:
    description: Load world
  moreworld.unload:
    description: Unload world

commands:
  moreworld:
    aliases: [mw]
    permission: moreworld.command
